name: C/C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install all C depedencies
      run: sudo apt install libconfig-dev
    - name : Create output folder
      run : mkdir output 
    - name : Make server program
      run : make server
    - name : Make client program
      run : make client
    - name : give rights 
      run : sudo chmod u+x test_launch.sh
    - name : Execute launch sequence
      run : ./test_launch.sh 
